"""
synthetic_proposals_extended.py
40 research proposals for the diagnostic methodology study.

First 20 entries are the original evaluation corpus preserved verbatim
(with info_sufficiency_expected / rationale backfilled, and source filled
where it was missing). Entries P21–P40 are new proposals targeting Medium/Low
coverage, contested Charter cases, non-Western contexts, and framework tension.

Generated by diagnostic/corpus_expansion.py — re-run that script to regenerate.
Do not introduce a branded acronym for the diagnostic methodology in this file.
"""

PROPOSALS = [
    {'id': 'P01',
     'title': 'Optum Health Risk Stratification Algorithm',
     'risk_level': 'High',
     'source': 'Obermeyer, Z., Powers, B., Vogeli, C., & Mullainathan, S. (2019). Dissecting racial '
               'bias in an algorithm used to manage the health of populations. Science, 366(6464), '
               '447–453. DOI: 10.1126/science.aax2342',
     'proposal_text': 'This research proposes to develop a commercial health risk stratification '
                      'algorithm to identify high-need patients for enrolment in care management '
                      'programmes across a network of US hospital systems. The algorithm will use '
                      'insurance claims data as a proxy for health need, predicting which patients '
                      'require additional clinical resources based on historical healthcare costs, '
                      'prior diagnoses, medication use, and utilisation patterns from electronic '
                      'health records covering approximately 200 million patients annually. Patients '
                      'scoring in the top 3 percentile will automatically be referred to care '
                      'management; those in the top 45 percentile will be assessed for referral. The '
                      'algorithm will not explicitly use race as a predictive variable. However, '
                      'because Black patients have historically incurred lower healthcare costs than '
                      'white patients with equivalent chronic disease burden — due to structural '
                      'barriers to healthcare access including cost, discrimination, and geographic '
                      'distance — the cost proxy will systematically underestimate the health needs of '
                      'Black patients. The algorithm has not undergone independent bias auditing prior '
                      'to deployment. No mechanism for algorithmic review or patient appeal of care '
                      'management non-referral decisions is planned.',
     'expected_requirements': ['R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'AI021',
                               'AI024',
                               'HE012',
                               'HE015',
                               'ACM001',
                               'ACM002'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art35_HealthCare',
                         'Art8_DataProtection',
                         'Art2_RightToLife'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art35_HealthCare',
                                   'Art8_DataProtection',
                                   'Art2_RightToLife'],
     'expected_risks': ['Discrimination', 'PhysicalHarm'],
     'expected_risk_categories': ['Discrimination', 'PhysicalHarm'],
     'info_sufficiency_expected': 5,
     'rationale': 'Well-documented racial bias via cost proxy; articles and risks are clear.'},

    {'id': 'P02',
     'title': 'COMPAS Recidivism Risk Assessment Tool',
     'risk_level': 'High',
     'source': 'Angwin, J., Larson, J., Mattu, S., & Kirchner, L. (2016). Machine Bias. ProPublica. '
               'https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing',
     'proposal_text': 'This research proposes to deploy the COMPAS (Correctional Offender Management '
                      'Profiling for Alternative Sanctions) risk assessment tool across criminal '
                      "courts in Broward County, Florida, to predict defendants' likelihood of "
                      'recidivism. The system uses a proprietary algorithm trained on a battery of '
                      'psychological questionnaire responses administered at the time of arrest, '
                      'combined with criminal history variables including prior arrest count, age at '
                      'first offence, and charge severity. The algorithm produces three decile scores '
                      '(1–10) for general recidivism, violent recidivism, and failure to appear, with '
                      'scores categorised as Low (1–4), Medium (5–7), or High (8–10). These scores '
                      'will be provided to judges and parole officers at pre-trial hearings and '
                      'sentencing to inform detention and release decisions. The model is proprietary '
                      'and its internal weighting is not disclosed to defendants or defence counsel. '
                      'No mechanism for defendants to challenge the algorithmic risk score is included '
                      "in the deployment design. An independent analysis of the algorithm's outputs "
                      'found that Black defendants who did not re-offend were falsely classified as '
                      'high risk at nearly twice the rate of white defendants who did not re-offend '
                      '(45% vs 24%).',
     'expected_requirements': ['R010',
                               'R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'AI021',
                               'AI022',
                               'HE005',
                               'ACM001',
                               'ACM024'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art6_RightToLiberty',
                         'Art47_RightToEffectiveRemedy',
                         'Art48_PresumptionOfInnocence'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art6_RightToLiberty',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art48_PresumptionOfInnocence'],
     'expected_risks': ['Discrimination', 'LibertyViolation'],
     'expected_risk_categories': ['Discrimination', 'LibertyViolation'],
     'info_sufficiency_expected': 5,
     'rationale': 'Proprietary recidivism tool with documented disparate false-positive rates.'},

    {'id': 'P03',
     'title': 'Amazon Rekognition Law Enforcement Facial Recognition',
     'risk_level': 'High',
     'source': "Snow, J. (2018). Amazon Is Selling Facial Recognition to Law Enforcement — and It's "
               'Cause for Concern. ACLU. '
               'https://www.aclu.org/news/privacy-technology/amazon-teams-government-deploy-dangerous-new; '
               'Raji, I.D. & Buolamwini, J. (2019). Actionable Auditing. AAAI/ACM AIES 2019.',
     'proposal_text': 'This research proposes to deploy Amazon Rekognition, a cloud-based facial '
                      'recognition system, for use by law enforcement agencies across the United '
                      'States to identify individuals in real-time surveillance footage, body camera '
                      'recordings, and crime scene images. The system can identify and track up to 100 '
                      'faces in a single image and match them against databases of tens of millions of '
                      'faces drawn from arrest records and public sources. The system will be marketed '
                      'to local police departments as a tool for identifying persons of interest in '
                      'criminal investigations. The default confidence threshold of 80% will be used '
                      'for initial deployment, with Amazon recommending a 99% threshold for law '
                      'enforcement use — a discrepancy between default settings and recommended '
                      'settings that has not been addressed in the deployment contract. An ACLU audit '
                      'found that at 80% confidence, Rekognition falsely matched 28 members of the US '
                      'Congress to criminal mugshots, with disproportionate false positives for people '
                      'of colour including six members of the Congressional Black Caucus. No '
                      'independent demographic bias audit has been conducted prior to law enforcement '
                      'deployment. No independent oversight mechanism or accountability framework for '
                      'false match consequences has been established.',
     'expected_requirements': ['R010',
                               'R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI011',
                               'AI016',
                               'AI021',
                               'HE007',
                               'ACM001',
                               'ACM002'],
     'expected_rights': ['Art7_PrivateLife',
                         'Art8_DataProtection',
                         'Art21_NonDiscrimination',
                         'Art6_RightToLiberty',
                         'Art47_RightToEffectiveRemedy',
                         'Art48_PresumptionOfInnocence'],
     'expected_charter_articles': ['Art7_PrivateLife',
                                   'Art8_DataProtection',
                                   'Art21_NonDiscrimination',
                                   'Art6_RightToLiberty',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art48_PresumptionOfInnocence'],
     'expected_risks': ['Discrimination', 'Surveillance', 'FalseIdentification'],
     'expected_risk_categories': ['Discrimination', 'Surveillance', 'FalseIdentification'],
     'info_sufficiency_expected': 5,
     'rationale': 'Law-enforcement facial recognition with published false-match audit.'},

    {'id': 'P04',
     'title': 'Facebook Ad Delivery Discriminatory Optimisation',
     'risk_level': 'High',
     'source': 'Ali, M., Sapiezynski, P., Bogen, M., Korolova, A., Mislove, A., & Rieke, A. (2019). '
               "Discrimination through Optimization: How Facebook's Ad Delivery Can Lead to Skewed "
               'Outcomes. ACM CSCW 2019. DOI: 10.1145/3359301',
     'proposal_text': 'This research proposes to develop a machine learning-based ad delivery '
                      'optimisation system for deployment on a major social media platform. The system '
                      'will use a multi-objective optimisation algorithm that maximises ad relevance '
                      'scores and advertiser return on investment by predicting which users are most '
                      'likely to engage with each advertisement. The algorithm will use thousands of '
                      'user behavioural, demographic, and interest signals — excluding explicit race '
                      'and gender variables — to determine ad delivery. The system will operate as a '
                      'real-time auction where advertisers bid for impression opportunities, with the '
                      "platform's relevance prediction model determining which users see which ads. An "
                      'academic audit of this system found that even when advertisers set their '
                      'targeting parameters to be fully inclusive with no demographic restrictions, '
                      'the optimisation algorithm delivered employment ads predominantly to men and '
                      'housing ads predominantly to white users. This skew was caused by the '
                      "algorithm's financial optimisation function, which learned that majority-group "
                      'users were cheaper to reach and more likely to engage. The system does not '
                      'include pre-deployment fairness auditing. No mechanism for individual users to '
                      'understand why they are or are not shown specific opportunity-related '
                      'advertisements is planned.',
     'expected_requirements': ['R010',
                               'R027',
                               'R042',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'AI021',
                               'HE012',
                               'HE013',
                               'HE015',
                               'ACM001',
                               'ACM002',
                               'ACM012'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art23_GenderEquality',
                         'Art15_FreedomOfOccupation',
                         'Art8_DataProtection'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art23_GenderEquality',
                                   'Art15_FreedomOfOccupation',
                                   'Art8_DataProtection'],
     'expected_risks': ['Discrimination', 'EmploymentHarm', 'EconomicHarm'],
     'expected_risk_categories': ['Discrimination', 'EmploymentHarm', 'EconomicHarm'],
     'info_sufficiency_expected': 4,
     'rationale': 'Ad-delivery optimisation produces demographic skew without explicit protected '
                  'attributes.'},

    {'id': 'P05',
     'title': 'NHS Sepsis Prediction Algorithm with Racial Bias',
     'risk_level': 'High',
     'source': 'Bhatt, D.L. et al. (2021). Cited in: Guardian (2021). NHS AI tool may discriminate '
               'against patients with black and minority ethnic backgrounds. '
               'https://www.theguardian.com/society/2021/jun/11/nhs-ai-tool-may-discriminate-against-patients-with-black-and-minority-ethnic-backgrounds; '
               'Chua et al. (2025). The role of AI in sepsis in the Emergency Department. Annals of '
               'Translational Medicine.',
     'proposal_text': 'This research proposes to deploy a machine learning sepsis prediction algorithm '
                      'across NHS England hospital trusts to identify patients at risk of sepsis '
                      'deterioration in emergency department and ward settings. The algorithm uses '
                      'physiological parameters including respiratory rate, oxygen saturation, '
                      'temperature, systolic blood pressure, pulse rate, and level of consciousness — '
                      'as recorded in the National Early Warning Score 2 (NEWS2) framework — alongside '
                      'laboratory values and electronic health record data, to generate real-time risk '
                      'scores for clinical staff. The training dataset was drawn predominantly from '
                      'NHS patient records which have documented under-representation of Black, Asian, '
                      'and minority ethnic patient populations in specialist care pathways. Academic '
                      'analysis has found that vital signs used as predictive features are racially '
                      'skewed, as minority patients may exhibit different baseline physiological '
                      'profiles than the majority-white training population. The algorithm has not '
                      'undergone prospective demographic bias auditing across ethnic subgroups prior '
                      'to nationwide deployment. Clinical staff will receive risk scores without '
                      "visibility into the algorithm's feature weighting or demographic performance "
                      'variance. No formal mechanism for clinicians to record or escalate concerns '
                      'about demographic performance disparities is included in the deployment '
                      'framework.',
     'expected_requirements': ['R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI008',
                               'AI016',
                               'AI024',
                               'HE012',
                               'HE015',
                               'ACM001',
                               'ACM014'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art35_HealthCare',
                         'Art2_RightToLife',
                         'Art8_DataProtection'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art35_HealthCare',
                                   'Art2_RightToLife',
                                   'Art8_DataProtection'],
     'expected_risks': ['Discrimination', 'PhysicalHarm'],
     'expected_risk_categories': ['Discrimination', 'PhysicalHarm'],
     'info_sufficiency_expected': 4,
     'rationale': 'Clinical sepsis model with under-represented minority training data.'},

    {'id': 'P06',
     'title': 'Emotion Recognition in Secondary School Classrooms',
     'risk_level': 'High',
     'proposal_text': 'This project proposes to install camera-based emotion recognition systems in '
                      'six secondary school classrooms in Dublin to study the relationship between '
                      'student emotional engagement and learning outcomes. The system will use '
                      'computer vision to classify student facial expressions into six emotional '
                      'categories (happy, sad, angry, surprised, fearful, neutral) at 5-second '
                      'intervals throughout lessons. Data will be collected over one academic term '
                      'covering approximately 180 students aged 13-17. Parental consent will be '
                      'obtained but students will not be given an individual opt-out mechanism that '
                      'allows them to remain in the classroom without being monitored. The emotion '
                      'recognition system has been validated primarily on adult Western faces and has '
                      'not been tested for accuracy on adolescent faces or faces from diverse ethnic '
                      'backgrounds. Aggregated emotional engagement scores will be shared with '
                      'teachers to inform pedagogical adjustments.',
     'expected_requirements': ['R027',
                               'R042',
                               'R043',
                               'R044',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI011',
                               'AI016',
                               'HE003',
                               'ACM004',
                               'ACM005'],
     'expected_rights': ['Art24_RightsOfChild',
                         'Art7_PrivateLife',
                         'Art8_DataProtection',
                         'Art1_HumanDignity',
                         'Art3_RightToIntegrity'],
     'expected_charter_articles': ['Art24_RightsOfChild',
                                   'Art7_PrivateLife',
                                   'Art8_DataProtection',
                                   'Art1_HumanDignity',
                                   'Art3_RightToIntegrity'],
     'expected_risks': ['ChildrenRights', 'PrivacyBreach', 'Discrimination'],
     'expected_risk_categories': ['ChildrenRights', 'PrivacyBreach', 'Discrimination'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 4,
     'rationale': 'Classroom emotion recognition on minors without individual opt-out.'},

    {'id': 'P07',
     'title': 'NLP Sentiment Analysis on Student Essay Submissions',
     'risk_level': 'Medium',
     'proposal_text': 'This research proposes to apply sentiment analysis and linguistic style '
                      'detection to a corpus of 5,000 anonymised undergraduate essays submitted to the '
                      'School of English at Trinity College Dublin. The aim is to investigate whether '
                      'emotional tone and writing style correlate with academic grade outcomes. Essays '
                      'will be collected from the past three academic years with student consent '
                      'obtained retrospectively via email. The NLP pipeline will extract features '
                      'including sentiment polarity, subjectivity scores, vocabulary complexity, and '
                      'sentence structure patterns. The researchers will investigate whether '
                      "detectable stylistic differences correlate with students' first language, "
                      'gender, or socioeconomic background as indicated by fee status. All analysis '
                      'will be performed on pseudonymised data with student IDs replaced by random '
                      'codes. Results will be published in aggregate form only.',
     'expected_requirements': ['R005',
                               'R023',
                               'R027',
                               'R042',
                               'R054',
                               'R085',
                               'HE007',
                               'HE012',
                               'ACM003',
                               'ACM012'],
     'expected_rights': ['Art8_DataProtection', 'Art21_NonDiscrimination', 'Art7_PrivateLife'],
     'expected_charter_articles': ['Art8_DataProtection',
                                   'Art21_NonDiscrimination',
                                   'Art7_PrivateLife'],
     'expected_risks': ['Discrimination', 'PrivacyBreach'],
     'expected_risk_categories': ['Discrimination', 'PrivacyBreach'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 3,
     'rationale': 'Retrospective essay NLP; consent and discrimination risks are partially specified.'},

    {'id': 'P08',
     'title': 'AI Chatbot for Mental Health Support Triage',
     'risk_level': 'Medium',
     'proposal_text': 'This project proposes to develop a conversational AI chatbot to provide initial '
                      'mental health support triage for university students. The chatbot will conduct '
                      'a structured conversational assessment to evaluate symptoms of anxiety and '
                      'depression using validated clinical screening instruments (PHQ-9, GAD-7) '
                      'adapted into conversational format. Based on the assessment, the chatbot will '
                      'recommend one of three pathways: self-help resources, a scheduled counselling '
                      'appointment, or immediate crisis intervention referral. The chatbot will store '
                      'conversation logs for quality improvement purposes. Student data will be '
                      'pseudonymised but linked to student records to enable follow-up. The chatbot '
                      'will include a disclaimer that it is not a substitute for professional mental '
                      'health care. The system has not been validated against clinical assessments '
                      'performed by qualified professionals. Conversations will be processed by an '
                      'external cloud-based NLP service.',
     'expected_requirements': ['R021',
                               'R027',
                               'R042',
                               'R054',
                               'R071',
                               'AI001',
                               'AI008',
                               'AI024',
                               'HE003',
                               'HE017',
                               'ACM001'],
     'expected_rights': ['Art35_HealthCare',
                         'Art2_RightToLife',
                         'Art8_DataProtection',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art35_HealthCare',
                                   'Art2_RightToLife',
                                   'Art8_DataProtection',
                                   'Art1_HumanDignity'],
     'expected_risks': ['PhysicalHarm', 'PrivacyBreach'],
     'expected_risk_categories': ['PhysicalHarm', 'PrivacyBreach'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 3,
     'rationale': 'Mental-health triage chatbot; clinical validation gap is stated but severity is '
                  'judgemental.'},

    {'id': 'P09',
     'title': 'Intelligent Academic Advising Recommendation System',
     'risk_level': 'Medium',
     'proposal_text': 'This research proposes to build a recommendation system for academic module '
                      'selection at Trinity College Dublin. The system will analyse historical student '
                      'records including module choices, grades achieved, attendance patterns, and '
                      'degree outcomes to recommend optimal module combinations for current students. '
                      'The dataset covers 20,000 student records from the past ten years. Students '
                      'will receive personalised module recommendations through the student portal '
                      'alongside existing manual advising. The system will use collaborative filtering '
                      'to identify students with similar academic profiles and recommend modules that '
                      'led to positive outcomes for comparable students. The researchers acknowledge '
                      'that historical patterns may reflect systemic inequalities in module access and '
                      'outcomes. The model will not account for disability accommodations or students '
                      'who changed programmes. Student consent for the use of historical academic '
                      'records in the training dataset has not been explicitly obtained.',
     'expected_requirements': ['R005',
                               'R023',
                               'R027',
                               'R042',
                               'R054',
                               'R085',
                               'AI012',
                               'HE007',
                               'HE011',
                               'ACM003'],
     'expected_rights': ['Art8_DataProtection', 'Art21_NonDiscrimination', 'Art41_GoodAdministration'],
     'expected_charter_articles': ['Art8_DataProtection',
                                   'Art21_NonDiscrimination',
                                   'Art41_GoodAdministration'],
     'expected_risks': ['Discrimination', 'PrivacyBreach'],
     'expected_risk_categories': ['Discrimination', 'PrivacyBreach'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 3,
     'rationale': 'Module recommender on historical records; consent gap clear, harm pathway less so.'},

    {'id': 'P10',
     'title': 'Social Media Misinformation Detection Tool',
     'risk_level': 'Medium',
     'proposal_text': 'This project aims to develop an NLP-based tool for detecting health-related '
                      'misinformation on Irish social media platforms. The system will collect public '
                      'posts from Twitter/X, Reddit, and Facebook groups discussing topics including '
                      'vaccination, cancer treatments, and mental health remedies. The tool will '
                      'classify posts as verified, unverified, or misleading using a combination of '
                      'source credibility scoring and claim verification against WHO and HSE published '
                      'guidelines. The dataset will include approximately 500,000 public posts '
                      'collected via platform APIs. While posts are publicly available, the tool will '
                      'process usernames and account metadata to assess source credibility patterns. '
                      'The researchers plan to publish a list of accounts identified as frequent '
                      'misinformation sources. The tool does not account for satire, cultural context, '
                      'or legitimate medical debate where scientific consensus has not been '
                      'established.',
     'expected_requirements': ['R001',
                               'R010',
                               'R019',
                               'R027',
                               'R054',
                               'AI001',
                               'HE019',
                               'HE021',
                               'ACM020',
                               'ACM025'],
     'expected_rights': ['Art11_FreedomOfExpression', 'Art7_PrivateLife', 'Art8_DataProtection'],
     'expected_charter_articles': ['Art11_FreedomOfExpression',
                                   'Art7_PrivateLife',
                                   'Art8_DataProtection'],
     'expected_risks': ['PrivacyBreach', 'ExpressionHarm'],
     'expected_risk_categories': ['PrivacyBreach', 'ExpressionHarm'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 3,
     'rationale': 'Misinformation detector; expression vs safety trade-off is contested.'},

    {'id': 'P11',
     'title': 'Automated Essay Grading System',
     'risk_level': 'Medium',
     'proposal_text': 'This research proposes to develop an automated essay grading system for '
                      'first-year undergraduate modules at Trinity College Dublin. The system will use '
                      'large language model embeddings to score essays on a 0-100 scale by comparing '
                      'them against a rubric-encoded scoring model trained on 3,000 previously graded '
                      'essays. The system will provide both a numerical grade and written feedback '
                      'comments generated by the LLM. The tool is intended to reduce marking workload '
                      'by providing initial scores that lecturers can review and adjust. The training '
                      'data consists of essays graded by twelve different tutors whose grading '
                      'standards varied considerably. Students whose first language is not English may '
                      "receive systematically different scores due to the model's sensitivity to "
                      'grammatical patterns associated with non-native speakers. Students will not be '
                      'informed that AI-assisted grading is being used. No appeals process '
                      'specifically addressing algorithmic grading errors has been designed.',
     'expected_requirements': ['R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'AI017',
                               'HE012',
                               'ACM002',
                               'ACM013'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art41_GoodAdministration',
                         'Art47_RightToEffectiveRemedy'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art41_GoodAdministration',
                                   'Art47_RightToEffectiveRemedy'],
     'expected_risks': ['Discrimination', 'Accountability'],
     'expected_risk_categories': ['Discrimination', 'Accountability'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 4,
     'rationale': 'Automated grading with L1 bias and no AI-specific appeal path.'},

    {'id': 'P12',
     'title': 'ML Model for Hospital Bed Allocation',
     'risk_level': 'Medium',
     'proposal_text': 'This research proposes to develop a machine learning model to optimise hospital '
                      'bed allocation across three Dublin hospitals. The model will predict patient '
                      'length of stay, readmission risk, and discharge timing using electronic health '
                      'records including diagnosis codes, vital signs, medication history, and '
                      'demographic information including age, gender, and medical card status. The '
                      'training dataset consists of 80,000 anonymised patient records from 2018-2024. '
                      'The model will generate daily recommendations for bed managers on patient '
                      'transfers and early discharge candidates. The researchers acknowledge that '
                      'medical card status (a proxy for socioeconomic deprivation) could influence the '
                      "model's predictions in ways that disadvantage lower-income patients. The model "
                      "outputs will be advisory but will be integrated into the hospital's electronic "
                      'patient record system. No mechanism for clinical override documentation has '
                      'been designed.',
     'expected_requirements': ['R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI008',
                               'AI024',
                               'HE003',
                               'ACM001',
                               'ACM014'],
     'expected_rights': ['Art35_HealthCare',
                         'Art21_NonDiscrimination',
                         'Art2_RightToLife',
                         'Art8_DataProtection'],
     'expected_charter_articles': ['Art35_HealthCare',
                                   'Art21_NonDiscrimination',
                                   'Art2_RightToLife',
                                   'Art8_DataProtection'],
     'expected_risks': ['Discrimination', 'PhysicalHarm'],
     'expected_risk_categories': ['Discrimination', 'PhysicalHarm'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 4,
     'rationale': 'Bed allocation using medical-card status as a socioeconomic proxy.'},

    {'id': 'P13',
     'title': 'Bibliometric Analysis of Open Access AI Ethics Publications',
     'risk_level': 'Low',
     'proposal_text': 'This research proposes to conduct a bibliometric analysis of peer-reviewed '
                      'publications on AI ethics from 2018-2025. The study will use the Scopus and Web '
                      'of Science databases to identify all publications containing keywords related '
                      'to AI ethics, responsible AI, algorithmic fairness, and AI governance. The '
                      'analysis will examine publication trends, citation networks, geographic '
                      'distribution of research groups, and thematic clustering using topic modelling. '
                      'All data is publicly available metadata from academic databases. No personal '
                      'data about individual researchers will be collected beyond publicly listed '
                      'author names and institutional affiliations. The analysis will use standard '
                      'bibliometric tools including VOSviewer and Bibliometrix. Results will identify '
                      'gaps in the AI ethics literature to inform future research directions. No AI '
                      'systems will be developed or deployed as part of this research.',
     'expected_requirements': ['R001', 'R006', 'R057', 'HE023', 'ACM018'],
     'expected_rights': ['Art11_FreedomOfExpression'],
     'expected_charter_articles': ['Art11_FreedomOfExpression'],
     'expected_risks': [],
     'expected_risk_categories': [],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 5,
     'rationale': 'Bibliometric metadata only; no personal data or deployment.'},

    {'id': 'P14',
     'title': 'NLP-Assisted Systematic Literature Review Tool',
     'risk_level': 'Low',
     'proposal_text': 'This project aims to develop an NLP pipeline to assist researchers in '
                      'conducting systematic literature reviews. The tool will automate the screening '
                      'of academic paper abstracts against predefined inclusion and exclusion '
                      'criteria, reducing the manual workload of the initial screening phase. The '
                      'system will use pre-trained transformer models to classify abstracts as '
                      'relevant or irrelevant based on researcher-defined criteria. The tool will be '
                      'evaluated on a benchmark of three previously completed systematic reviews where '
                      'human screening decisions are available as ground truth. All data consists of '
                      'publicly available academic abstracts. The tool will provide a confidence score '
                      'alongside each classification to guide manual verification. The researchers '
                      'will open-source the tool for academic use. No personal data is involved at any '
                      'stage.',
     'expected_requirements': ['R001', 'R054', 'R057', 'HE023', 'ACM018', 'ACM029'],
     'expected_rights': ['Art11_FreedomOfExpression'],
     'expected_charter_articles': ['Art11_FreedomOfExpression'],
     'expected_risks': [],
     'expected_risk_categories': [],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 5,
     'rationale': 'Literature-screening tool on public abstracts; no personal data.'},

    {'id': 'P15',
     'title': 'Public Transport Usage Pattern Analysis',
     'risk_level': 'Low',
     'proposal_text': 'This research proposes to analyse anonymised Dublin Bus and Luas smart card '
                      'tap-on data to model public transport usage patterns across different times of '
                      'day, routes, and weather conditions. The dataset consists of aggregated journey '
                      'counts per route per hour provided by the National Transport Authority under an '
                      'open data licence. No individual passenger records are included and no '
                      're-identification is possible from the aggregated data. The analysis will use '
                      'time series forecasting and clustering algorithms to identify underserved '
                      'routes and peak demand periods. Results will be shared with Dublin City Council '
                      'to inform transport planning decisions. The environmental impact of the '
                      'computational resources required for the analysis will be documented. No AI '
                      'system will be deployed in any operational context.',
     'expected_requirements': ['R001', 'R052', 'R057', 'HE018', 'HE023', 'ACM026'],
     'expected_rights': ['Art37_EnvironmentalProtection'],
     'expected_charter_articles': ['Art37_EnvironmentalProtection'],
     'expected_risks': [],
     'expected_risk_categories': [],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 5,
     'rationale': 'Aggregated open transport counts; re-identification not feasible as described.'},

    {'id': 'P16',
     'title': 'Climate Dataset Trend Analysis Using Statistical ML',
     'risk_level': 'Low',
     'proposal_text': 'This project proposes to apply statistical machine learning methods to publicly '
                      'available climate datasets from Met Éireann and the European Centre for '
                      'Medium-Range Weather Forecasts. The research will analyse temperature, '
                      'precipitation, and wind patterns across Ireland over the past 50 years to '
                      'identify statistically significant trends and regional variations. The '
                      'methodology combines Gaussian process regression with ensemble methods to '
                      'quantify prediction uncertainty. All datasets are publicly available under open '
                      'government data licences. No personal data is involved. The computational '
                      'resources required for model training will be documented including estimated '
                      'carbon footprint using the ML CO2 Impact calculator. Results will be published '
                      'as an open-access paper with all code and data made available in a public '
                      'repository.',
     'expected_requirements': ['R001', 'R052', 'R057', 'HE018', 'HE023', 'ACM026', 'ACM038'],
     'expected_rights': ['Art37_EnvironmentalProtection'],
     'expected_charter_articles': ['Art37_EnvironmentalProtection'],
     'expected_risks': [],
     'expected_risk_categories': [],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 5,
     'rationale': 'Public climate datasets; environmental documentation only.'},

    {'id': 'P17',
     'title': 'Dual-Use AI for Detecting Online Extremist Content',
     'risk_level': 'High',
     'proposal_text': 'This research proposes to develop an NLP classifier to detect extremist '
                      'recruitment content on social media platforms including Telegram, Twitter/X, '
                      'and encrypted messaging forums. The classifier will be trained on a dataset of '
                      '20,000 annotated posts collected from known extremist channels alongside 20,000 '
                      'non-extremist posts covering political activism, religious discussion, and '
                      'protest organisation. The system must distinguish between legitimate political '
                      'expression and genuine incitement to violence. The training data includes '
                      'content in English, Arabic, and Irish. The researchers acknowledge the dual-use '
                      'risk that the classifier could be repurposed for political censorship or '
                      'suppression of minority viewpoints by authoritarian actors. The tool will be '
                      'developed as open-source software. No content moderation decisions will be '
                      'automated. The research does not include engagement with affected communities '
                      'or civil liberties organisations in the design process.',
     'expected_requirements': ['R001',
                               'R010',
                               'R019',
                               'R027',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'HE005',
                               'HE019',
                               'HE021',
                               'ACM020',
                               'ACM025'],
     'expected_rights': ['Art11_FreedomOfExpression',
                         'Art12_FreedomOfAssembly',
                         'Art21_NonDiscrimination',
                         'Art1_HumanDignity',
                         'Art7_PrivateLife'],
     'expected_charter_articles': ['Art11_FreedomOfExpression',
                                   'Art12_FreedomOfAssembly',
                                   'Art21_NonDiscrimination',
                                   'Art1_HumanDignity',
                                   'Art7_PrivateLife'],
     'expected_risks': ['Discrimination', 'ExpressionHarm', 'DualUseMisuse'],
     'expected_risk_categories': ['Discrimination', 'ExpressionHarm', 'DualUseMisuse'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 2,
     'rationale': 'Dual-use extremist-content classifier; Art.11 vs safety is genuinely contested.'},

    {'id': 'P18',
     'title': 'Agentic AI Research Assistant with Web Access',
     'risk_level': 'High',
     'proposal_text': 'This project proposes to develop an autonomous AI research assistant capable of '
                      'independently searching the web, reading academic papers, summarising findings, '
                      'and drafting literature review sections. The agent will use a large language '
                      'model with tool-use capabilities including web browsing, PDF parsing, database '
                      'querying, and file creation. The agent will operate with minimal human '
                      'oversight, executing multi-step research tasks overnight and presenting results '
                      'for review the following morning. The system will access academic databases '
                      "using the researcher's institutional credentials. The agent may encounter and "
                      'process personal data, copyrighted material, and sensitive research findings '
                      'during its autonomous web browsing. No guardrails have been implemented to '
                      'prevent the agent from accessing restricted databases, submitting forms, or '
                      'interacting with external services beyond its intended scope. The researchers '
                      "plan to evaluate the agent's output quality but have not addressed "
                      'accountability for errors, hallucinated citations, or unintended data access.',
     'expected_requirements': ['R001',
                               'R010',
                               'R027',
                               'R054',
                               'R071',
                               'AI001',
                               'AI008',
                               'AI010',
                               'HE001',
                               'HE006',
                               'ACM001',
                               'ACM017'],
     'expected_rights': ['Art41_GoodAdministration',
                         'Art8_DataProtection',
                         'Art7_PrivateLife',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art41_GoodAdministration',
                                   'Art8_DataProtection',
                                   'Art7_PrivateLife',
                                   'Art1_HumanDignity'],
     'expected_risks': ['Accountability', 'PrivacyBreach', 'FunctionCreep'],
     'expected_risk_categories': ['Accountability', 'PrivacyBreach', 'FunctionCreep'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 4,
     'rationale': 'Autonomous research agent with weak guardrails; accountability risks clear.'},

    {'id': 'P19',
     'title': 'Cross-Border EU/US Medical Data Sharing for Rare Disease AI',
     'risk_level': 'High',
     'proposal_text': 'This research proposes a collaboration between Trinity College Dublin and Johns '
                      'Hopkins University to develop an AI diagnostic model for rare genetic '
                      'conditions. The project requires sharing patient genomic data and medical '
                      'imaging between Ireland and the United States. The Irish dataset of 2,000 '
                      'patients was collected under GDPR with consent for domestic research use only. '
                      'The US dataset was collected under HIPAA regulations. The researchers propose '
                      'to use federated learning to train the model without raw data leaving each '
                      'jurisdiction, but the federated learning protocol requires sharing model '
                      'gradient updates which have been shown in recent research to be vulnerable to '
                      'reconstruction attacks that can recover individual patient data. The project '
                      'has received funding approval but cross-border data transfer impact assessments '
                      'have not been completed. The rare disease patient population is small enough '
                      'that anonymisation may not prevent re-identification. No patient advisory group '
                      'has been consulted on the data sharing arrangements.',
     'expected_requirements': ['R005',
                               'R023',
                               'R024',
                               'R027',
                               'R029',
                               'R042',
                               'R054',
                               'R071',
                               'AI011',
                               'AI013',
                               'AI014',
                               'AI025',
                               'HE007',
                               'HE008',
                               'HE009',
                               'ACM003',
                               'ACM008'],
     'expected_rights': ['Art8_DataProtection',
                         'Art7_PrivateLife',
                         'Art35_HealthCare',
                         'Art2_RightToLife'],
     'expected_charter_articles': ['Art8_DataProtection',
                                   'Art7_PrivateLife',
                                   'Art35_HealthCare',
                                   'Art2_RightToLife'],
     'expected_risks': ['PrivacyBreach', 'DataBreach', 'PhysicalHarm'],
     'expected_risk_categories': ['PrivacyBreach', 'DataBreach', 'PhysicalHarm'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 4,
     'rationale': 'Cross-border genomic sharing with reconstruction-attack risk stated.'},

    {'id': 'P20',
     'title': 'Workplace Productivity Monitoring with Employee Consent',
     'risk_level': 'Medium',
     'proposal_text': 'This research proposes to study the relationship between digital workplace '
                      'behaviours and productivity by monitoring 200 consenting employees at a Dublin '
                      'technology company over six months. The monitoring system will track '
                      'application usage, email response times, meeting attendance, keyboard activity '
                      'patterns, and break frequency. All participants will provide written informed '
                      'consent and can withdraw at any time without workplace consequences. Data will '
                      'be stored on encrypted university servers and destroyed after the study period. '
                      'However, the monitoring software will also incidentally capture screen content '
                      'including potentially sensitive communications. Aggregate productivity patterns '
                      'will be shared with the employer in a format that does not identify individual '
                      'employees, but the small team sizes of 5-8 people within departments may enable '
                      'indirect identification. The employer has stated that monitoring results will '
                      'not influence performance reviews, but this commitment is not legally binding. '
                      'The research does not address the power imbalance between employer and employee '
                      'that may compromise the voluntariness of consent.',
     'expected_requirements': ['R001',
                               'R005',
                               'R010',
                               'R019',
                               'R023',
                               'R027',
                               'R042',
                               'R054',
                               'AI011',
                               'HE007',
                               'HE020',
                               'ACM003',
                               'ACM011'],
     'expected_rights': ['Art7_PrivateLife',
                         'Art8_DataProtection',
                         'Art31_FairWorkingConditions',
                         'Art15_FreedomOfOccupation'],
     'expected_charter_articles': ['Art7_PrivateLife',
                                   'Art8_DataProtection',
                                   'Art31_FairWorkingConditions',
                                   'Art15_FreedomOfOccupation'],
     'expected_risks': ['Surveillance', 'PrivacyBreach', 'EmploymentHarm'],
     'expected_risk_categories': ['Surveillance', 'PrivacyBreach', 'EmploymentHarm'],
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'info_sufficiency_expected': 3,
     'rationale': 'Workplace monitoring with formal consent but power-imbalance voluntariness '
                  'contested.'},

    {'id': 'P21',
     'title': 'Mobile-Money Credit Scoring in Kenya',
     'risk_level': 'Medium',
     'source': 'Illustrative case informed by: Berg, T. et al. (2020). On the Rise of FinTechs—Credit '
               'Scoring Using Digital Footprints. Review of Financial Studies; and Kenya Data '
               'Protection Act 2019 debates on alternative-data lending.',
     'proposal_text': 'This research proposes to develop a machine learning credit-scoring model for a '
                      'Nairobi-based digital lender serving unbanked and underbanked borrowers across '
                      'Kenya. The model will predict default risk from mobile-money transaction '
                      'histories, airtime purchase patterns, geolocation of cash-in/cash-out agents, '
                      'phone contacts graph density, and device metadata. Training data cover '
                      'approximately 2.4 million customers of a partner mobile-network operator, '
                      "collected under the operator's terms of service rather than purpose-specific "
                      'lending consent. Loan approval and pricing decisions will be fully automated '
                      'for amounts under KES 50,000, with no human review unless the applicant '
                      'formally complains. The researchers note that contact-graph features may encode '
                      'ethnicity and socioeconomic clustering in urban informal settlements, but no '
                      'demographic fairness audit across ethnic groups or counties is planned before '
                      'pilot launch. Rejected applicants will receive a generic adverse-action notice '
                      'without feature-level explanation. The study protocol has not yet been reviewed '
                      'against the Kenya Data Protection Act 2019 or the EU Charter articles that '
                      'would apply if the same pipeline were later ported to an EU migrant-lending '
                      'product.',
     'expected_requirements': ['R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'HE012',
                               'ACM001',
                               'ACM002'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art8_DataProtection',
                         'Art47_RightToEffectiveRemedy',
                         'Art15_FreedomOfOccupation'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art8_DataProtection',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art15_FreedomOfOccupation'],
     'expected_risks': ['Discrimination', 'EconomicHarm', 'PrivacyBreach'],
     'expected_risk_categories': ['Discrimination', 'EconomicHarm', 'PrivacyBreach'],
     'info_sufficiency_expected': 4,
     'rationale': 'Automated lending on alternative data with contact-graph proxies is a clear '
                  'Medium-risk discrimination and remedy case in a non-Western deployment context.'},

    {'id': 'P22',
     'title': 'Hiring Ranking Model with Caste-Correlated Proxies in India',
     'risk_level': 'High',
     'source': 'Illustrative case informed by Indian IT hiring audits and debates on caste '
               'discrimination in algorithmic recruitment (e.g. coverage in The Wire / Scroll on '
               'surname and education-network proxies).',
     'proposal_text': 'This research proposes to deploy a resume-ranking and interview-shortlisting '
                      'model across three large technology employers in Bengaluru and Hyderabad. The '
                      'model scores applicants using educational institution prestige, pin-code of '
                      'permanent address, parental occupation fields scraped from optional profile '
                      'forms, English-fluency estimates from writing samples, and historical hire '
                      'outcomes. Caste is not an explicit feature. Independent auditors have '
                      'previously shown that pin-code and institution features correlate strongly with '
                      'Scheduled-Caste and Scheduled-Tribe membership in several Indian metros. The '
                      'system will auto-reject the bottom 60% of applicants before any human recruiter '
                      'sees the file. Candidates will not be told that an algorithmic gate was used. '
                      'No caste-disaggregated fairness evaluation is included in the deployment plan, '
                      'and the employers assert that Indian constitutional protections against caste '
                      'discrimination do not require algorithmic audits. The research team has not '
                      'consulted Dalit or Adivasi employee resource groups.',
     'expected_requirements': ['R010',
                               'R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'AI021',
                               'HE012',
                               'ACM001',
                               'ACM002'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art15_FreedomOfOccupation',
                         'Art47_RightToEffectiveRemedy',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art15_FreedomOfOccupation',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art1_HumanDignity'],
     'expected_risks': ['Discrimination', 'EmploymentHarm'],
     'expected_risk_categories': ['Discrimination', 'EmploymentHarm'],
     'info_sufficiency_expected': 4,
     'rationale': 'High-risk automated hiring gate with documented proxy discrimination pathway in a '
                  'non-Western (India) context.'},

    {'id': 'P23',
     'title': 'Social-Benefit Eligibility Triage in Brazil',
     'risk_level': 'Medium',
     'source': 'Illustrative case informed by Brazil Cadastro Único / Bolsa Família digitalisation '
               'debates and Latin American social-protection algorithmic targeting literature.',
     'proposal_text': 'This project proposes a machine learning triage layer for a municipal '
                      'social-assistance programme in São Paulo that prioritises home visits for '
                      'families seeking cash-transfer enrolment. The model uses Cadastro Único '
                      'registry fields, utility payment irregularities, school attendance flags, and '
                      "neighbourhood vulnerability indices to score 'urgency'. Caseworkers will be "
                      'instructed to follow the ranked list unless they document an override. Families '
                      'scored as low-urgency may wait months for a visit. The training labels come '
                      'from past caseworker decisions, which community organisations argue '
                      'systematically under-served favelas and Afro-Brazilian households. No '
                      'disparate-impact audit by race or territory is scheduled. Applicants cannot see '
                      'their score or appeal the triage ranking—only the eventual eligibility decision '
                      'after a visit. The proposal notes tension with EU-style fundamental-rights '
                      'impact assessment expectations if the same pipeline were adapted under a '
                      'Horizon Europe social-innovation grant.',
     'expected_requirements': ['R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'HE012',
                               'HE015',
                               'ACM001'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art1_HumanDignity',
                         'Art47_RightToEffectiveRemedy',
                         'Art8_DataProtection'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art1_HumanDignity',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art8_DataProtection'],
     'expected_risks': ['Discrimination', 'EconomicHarm', 'Accountability'],
     'expected_risk_categories': ['Discrimination', 'EconomicHarm', 'Accountability'],
     'info_sufficiency_expected': 4,
     'rationale': 'Medium-risk welfare triage with proxy discrimination and weak appeal; non-Western '
                  '(Brazil) plus FRIA/Horizon tension note.'},

    {'id': 'P24',
     'title': 'Remote Exam Proctoring Across Southeast Asian Universities',
     'risk_level': 'Medium',
     'source': 'Illustrative case informed by Proctorio/ExamSoft controversies and ASEAN university '
               'emergency remote-assessment practices during and after COVID-19.',
     'proposal_text': 'This research proposes a shared remote-proctoring platform for five public '
                      'universities in Indonesia, Malaysia, and the Philippines. During timed exams, '
                      'the system records webcam video, microphone audio, screen activity, and '
                      "keystroke dynamics, flagging 'suspicious behaviour' via a proprietary model "
                      'trained primarily on North American student footage. Flagged sessions are '
                      'queued for human review; unflagged sessions are auto-cleared. Students in '
                      'shared housing report false flags when family members enter the frame. The '
                      'model has not been validated on darker skin tones under typical tropical indoor '
                      'lighting. Students must accept continuous recording to sit the exam; no '
                      'alternative invigilation path is offered. Recordings are retained for twelve '
                      'months on a Singapore cloud vendor. Universities have not published '
                      'false-positive rates by campus or demographic group.',
     'expected_requirements': ['R027',
                               'R042',
                               'R043',
                               'R054',
                               'R071',
                               'AI001',
                               'AI011',
                               'AI016',
                               'HE007',
                               'ACM004'],
     'expected_rights': ['Art7_PrivateLife',
                         'Art8_DataProtection',
                         'Art21_NonDiscrimination',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art7_PrivateLife',
                                   'Art8_DataProtection',
                                   'Art21_NonDiscrimination',
                                   'Art1_HumanDignity'],
     'expected_risks': ['PrivacyBreach', 'Discrimination', 'Surveillance'],
     'expected_risk_categories': ['PrivacyBreach', 'Discrimination', 'Surveillance'],
     'info_sufficiency_expected': 4,
     'rationale': 'Medium-risk biometric-adjacent proctoring with demographic validation gaps in '
                  'Southeast Asia.'},

    {'id': 'P25',
     'title': 'Arabic Social-Media Extremism Classifier for MENA Platforms',
     'risk_level': 'High',
     'source': 'Illustrative dual-use case informed by Arabic NLP moderation research and '
               'civil-society critiques of over-blocking political speech in MENA contexts.',
     'proposal_text': 'This research proposes an Arabic-dialect NLP classifier to detect extremist '
                      'recruitment and glorification of violence on public Telegram channels and '
                      'X/Twitter accounts across Egypt, Jordan, and Morocco. Training data mix '
                      'annotated jihadist propaganda with posts from secular activists, Islamist '
                      'electoral campaigns, and satire. The classifier will output a risk score used '
                      'by platform trust-and-safety teams to prioritise human review; scores above '
                      '0.85 will auto-suspend accounts for 48 hours pending review. Civil-society '
                      'partners warn that dialectal sarcasm and anti-regime protest slogans are '
                      'frequently mislabelled. The team plans open-source release of the model '
                      "weights. No engagement with journalists' unions or minority-rights groups is "
                      'scheduled. Whether Art.11 freedom of expression or public-security limitations '
                      'should dominate the rights analysis is deliberately left open in the '
                      'protocol—experts disagree.',
     'expected_requirements': ['R001',
                               'R010',
                               'R019',
                               'R027',
                               'R054',
                               'R071',
                               'AI001',
                               'HE005',
                               'HE019',
                               'ACM020',
                               'ACM025'],
     'expected_rights': ['Art11_FreedomOfExpression',
                         'Art12_FreedomOfAssembly',
                         'Art21_NonDiscrimination',
                         'Art7_PrivateLife'],
     'expected_charter_articles': ['Art11_FreedomOfExpression',
                                   'Art12_FreedomOfAssembly',
                                   'Art21_NonDiscrimination',
                                   'Art7_PrivateLife'],
     'expected_risks': ['ExpressionHarm', 'Discrimination', 'DualUseMisuse'],
     'expected_risk_categories': ['ExpressionHarm', 'Discrimination', 'DualUseMisuse'],
     'info_sufficiency_expected': 2,
     'rationale': 'Deliberately contested High-risk dual-use moderation case; Art.11 vs security is '
                  'expert-disputed even with adequate text.'},

    {'id': 'P26',
     'title': 'Smallholder Crop-Advisory Chatbot in Rural India',
     'risk_level': 'Low',
     'source': 'Illustrative case informed by Indian agri-advisory chatbots (e.g. Kisan Call Centre '
               'digitisation) and FAO discussions of AI for smallholder extension.',
     'proposal_text': 'This project proposes a WhatsApp-based crop-advisory chatbot for smallholder '
                      'farmers in Maharashtra and Odisha. The bot answers irrigation, pest, and '
                      'market-price questions using retrieval over public agricultural extension '
                      'bulletins and open weather APIs. Conversations are logged in aggregate for '
                      'service improvement; phone numbers are hashed after 30 days. No credit, '
                      'subsidy, or enforcement decisions are attached to bot use. A subtle residual '
                      'issue is that incorrect pest-treatment advice could cause crop loss for farmers '
                      'who treat the bot as authoritative, yet the interface presents answers with '
                      'high confidence and no uncertainty bands. The team will run a small accuracy '
                      'pilot against agronomist answers but has not planned liability or escalation '
                      'pathways when advice fails. No personal land-holding registries are ingested.',
     'expected_requirements': ['R001', 'R054', 'R057', 'AI008', 'HE023', 'ACM018'],
     'expected_rights': ['Art1_HumanDignity', 'Art8_DataProtection'],
     'expected_charter_articles': ['Art1_HumanDignity', 'Art8_DataProtection'],
     'expected_risks': ['Accountability'],
     'expected_risk_categories': ['Accountability'],
     'info_sufficiency_expected': 3,
     'rationale': 'Mostly Low-risk advisory tool; subtle over-confidence/accountability issue tests '
                  'under-flagging.'},

    {'id': 'P27',
     'title': 'Horizon Europe Biometric FRIA vs Open-Science Tension Study',
     'risk_level': 'High',
     'source': 'Synthetic case constructed to instantiate tension between EU AI Act Art.27 '
               'fundamental-rights impact assessment expectations for high-risk biometric systems and '
               'Horizon Europe open-science / data-sharing mandates.',
     'proposal_text': 'This Horizon Europe consortium proposes a multi-site study of gait-and-face '
                      'biometrics to recognise patients with rare neurological disorders across '
                      'clinics in Ireland, Germany, and Spain. The technical work package will train a '
                      'multimodal recognition model on clinic video and release model checkpoints and '
                      "a 'de-identified' embedding database under an open-science deliverable required "
                      'by the grant agreement. A parallel ethics work package notes that the same '
                      'system may qualify as high-risk biometric categorisation under the EU AI Act, '
                      'triggering an Art.27-style fundamental-rights impact assessment (FRIA) and '
                      'possibly restricting public release of embeddings. The consortium has not '
                      'resolved whether open deliverables or FRIA containment wins when they conflict. '
                      'Patient consent forms mention research use but not public model release. No '
                      'independent FRIA has been completed before the first data freeze.',
     'expected_requirements': ['R005',
                               'R023',
                               'R027',
                               'R042',
                               'R054',
                               'R071',
                               'AI011',
                               'AI013',
                               'HE007',
                               'HE008',
                               'HE009',
                               'ACM003',
                               'ACM008'],
     'expected_rights': ['Art8_DataProtection',
                         'Art7_PrivateLife',
                         'Art35_HealthCare',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art8_DataProtection',
                                   'Art7_PrivateLife',
                                   'Art35_HealthCare',
                                   'Art1_HumanDignity'],
     'expected_risks': ['PrivacyBreach', 'DataBreach', 'FunctionCreep'],
     'expected_risk_categories': ['PrivacyBreach', 'DataBreach', 'FunctionCreep'],
     'info_sufficiency_expected': 3,
     'rationale': 'Framework-tension case (AI Act FRIA vs Horizon open science); High risk, contested '
                  'compliance path.'},

    {'id': 'P28',
     'title': 'Municipal Permit Chatbot in Bogotá',
     'risk_level': 'Medium',
     'source': 'Illustrative case informed by Latin American govtech chatbot deployments and OAS/IDB '
               'discussions of automated administrative decisions.',
     'proposal_text': 'This research proposes a Spanish-language LLM chatbot that guides Bogotá '
                      'residents through business-permit and construction-licence applications. The '
                      'bot classifies query intent, retrieves municipal code passages, and drafts '
                      'application forms. In a pilot ward, incomplete answers that the bot labels '
                      "'likely ineligible' will auto-close the digital ticket without human review to "
                      'reduce backlog. Residents with limited literacy or non-standard Spanish '
                      'dialects may be disproportionately auto-closed. Conversation logs retain '
                      "national ID numbers entered into forms. The city asserts the bot is 'advisory "
                      "only,' yet ticket closure has the practical effect of a refusal. No "
                      'administrative-appeal pathway specific to bot closures is described.',
     'expected_requirements': ['R027', 'R042', 'R054', 'R071', 'AI001', 'AI017', 'HE011', 'ACM013'],
     'expected_rights': ['Art41_GoodAdministration',
                         'Art21_NonDiscrimination',
                         'Art47_RightToEffectiveRemedy',
                         'Art8_DataProtection'],
     'expected_charter_articles': ['Art41_GoodAdministration',
                                   'Art21_NonDiscrimination',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art8_DataProtection'],
     'expected_risks': ['Accountability', 'Discrimination', 'PrivacyBreach'],
     'expected_risk_categories': ['Accountability', 'Discrimination', 'PrivacyBreach'],
     'info_sufficiency_expected': 4,
     'rationale': 'Medium-risk automated administrative gatekeeping with remedy and discrimination '
                  'concerns in LatAm.'},

    {'id': 'P29',
     'title': 'Community Safety Hotspot Analytics without Arrest Prediction',
     'risk_level': 'Medium',
     'source': 'Illustrative contested case at the boundary of predictive policing critiques (e.g. Lum '
               "& Isaac; Chicago SSL debates) reframed as 'resource allocation'.",
     'proposal_text': "This project proposes a 'community safety analytics' dashboard for a mid-sized "
                      'EU city police service. The model forecasts week-ahead geographic '
                      'concentrations of emergency calls using historical CAD data, weather, and event '
                      'calendars. Outputs are heat maps for patrol allocation, not individual risk '
                      'scores. Civil-liberties groups argue the system recapitulates predictive '
                      'policing by intensifying presence in already over-policed neighbourhoods; the '
                      'police service argues it only allocates scarce ambulances and officers to call '
                      'volume. No individual surveillance cameras or stop-and-search recommendations '
                      'are generated. Historical call data embed prior discriminatory deployment '
                      'patterns. Whether Art.6 liberty, Art.21 non-discrimination, or neither is '
                      'primarily engaged is contested among reasonable experts given the '
                      'aggregate-only design.',
     'expected_requirements': ['R010', 'R027', 'R042', 'R054', 'R071', 'AI001', 'HE005', 'ACM001'],
     'expected_rights': ['Art21_NonDiscrimination', 'Art6_RightToLiberty', 'Art8_DataProtection'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art6_RightToLiberty',
                                   'Art8_DataProtection'],
     'expected_risks': ['Discrimination', 'Surveillance', 'LibertyViolation'],
     'expected_risk_categories': ['Discrimination', 'Surveillance', 'LibertyViolation'],
     'info_sufficiency_expected': 2,
     'rationale': 'Deliberately contested Medium case: aggregate hotspotting vs predictive policing; '
                  'article engagement disputed.'},

    {'id': 'P30',
     'title': 'Health Insurance Risk Pricing in South Africa',
     'risk_level': 'High',
     'source': 'Illustrative case informed by South African medical-scheme risk-rating debates and '
               'broader literature on algorithmic insurance discrimination.',
     'proposal_text': 'This research proposes a gradient-boosting model to set individual loading '
                      'factors for a private medical scheme in Johannesburg and Cape Town. Features '
                      'include claims history, pharmacy fills, wearable step counts (opt-in), and '
                      'residential suburb codes. Race is not an input, but suburb codes strongly proxy '
                      'apartheid-era spatial segregation. Members in the highest predicted-cost decile '
                      'face premium increases up to 40% or coverage exclusions for elective '
                      'procedures. The scheme plans no suburb- or race-disaggregated fairness audit, '
                      'citing proprietary actuarial practice. Members cannot obtain a meaningful '
                      "explanation of their loading beyond 'actuarial risk.' The National Health "
                      'Insurance reform context makes the private-scheme impact politically sensitive.',
     'expected_requirements': ['R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'AI021',
                               'HE012',
                               'ACM001',
                               'ACM002'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art35_HealthCare',
                         'Art8_DataProtection',
                         'Art47_RightToEffectiveRemedy'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art35_HealthCare',
                                   'Art8_DataProtection',
                                   'Art47_RightToEffectiveRemedy'],
     'expected_risks': ['Discrimination', 'EconomicHarm', 'PhysicalHarm'],
     'expected_risk_categories': ['Discrimination', 'EconomicHarm', 'PhysicalHarm'],
     'info_sufficiency_expected': 4,
     'rationale': 'High-risk insurance pricing with spatial proxies for race in South Africa; health '
                  'and remedy articles clear.'},

    {'id': 'P31',
     'title': 'Open African-Languages Speech Corpus with Personal Narratives',
     'risk_level': 'Low',
     'source': 'Illustrative case informed by Masakhane / Mozilla Common Voice African-language corpus '
               'efforts and consent debates around narrative speech data.',
     'proposal_text': 'This project will release an open speech corpus of 400 hours across Yoruba, '
                      'Igbo, and Swahili for ASR research. Speakers are paid volunteers who record '
                      'scripted sentences and optional two-minute personal stories about family and '
                      'work. Scripts are public-domain; personal stories may contain names, employers, '
                      'and locations. Release includes raw audio under CC-BY with speaker IDs replaced '
                      'by codes. A subtle issue: re-identification via voice biometrics plus story '
                      'content is possible for well-known community members, but the datasheet treats '
                      'the corpus as anonymised. No voice-biometric risk assessment is planned. '
                      'Otherwise the project is standard open-science language resource work with no '
                      'downstream decision system.',
     'expected_requirements': ['R001', 'R005', 'R023', 'R057', 'HE007', 'HE023', 'ACM003'],
     'expected_rights': ['Art8_DataProtection', 'Art7_PrivateLife'],
     'expected_charter_articles': ['Art8_DataProtection', 'Art7_PrivateLife'],
     'expected_risks': ['PrivacyBreach'],
     'expected_risk_categories': ['PrivacyBreach'],
     'info_sufficiency_expected': 3,
     'rationale': 'Low-risk open corpus with a subtle re-identification/voice issue to test '
                  'under-flagging.'},

    {'id': 'P32',
     'title': 'Aggregated Mobile-Money Flow Heatmaps for Urban Planning',
     'risk_level': 'Low',
     'source': 'Illustrative case informed by GSMA mobile-money analytics and urban-planning uses of '
               'aggregated transaction heatmaps in East Africa.',
     'proposal_text': 'This research proposes to publish weekly heatmaps of mobile-money cash-in and '
                      'cash-out volumes at 500-metre grid cells for Kampala, using operator data '
                      'aggregated under a national statistics memorandum. No individual wallet IDs are '
                      'released. The stated purpose is transit and market-infrastructure planning. A '
                      'subtle residual risk is that thin cells in peri-urban areas may still permit '
                      'inference about specific large traders when combined with public business '
                      "registries, yet the proposal asserts 'full anonymisation by aggregation.' No "
                      'attacker model or k-anonymity threshold is specified. No enforcement or tax '
                      'authority use is planned in the research protocol.',
     'expected_requirements': ['R001', 'R005', 'R023', 'R057', 'HE007', 'HE023'],
     'expected_rights': ['Art8_DataProtection', 'Art7_PrivateLife'],
     'expected_charter_articles': ['Art8_DataProtection', 'Art7_PrivateLife'],
     'expected_risks': ['PrivacyBreach'],
     'expected_risk_categories': ['PrivacyBreach'],
     'info_sufficiency_expected': 2,
     'rationale': 'Low-risk aggregated statistics with under-specified re-identification residual; '
                  'info-thin by design.'},

    {'id': 'P33',
     'title': 'University FAQ Chatbot Logging Student Queries',
     'risk_level': 'Low',
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'proposal_text': 'This project proposes an on-campus FAQ chatbot answering timetable, fee, and '
                      'library questions for undergraduate students. Queries are answered from a '
                      "curated knowledge base. For 'service improvement,' the system stores raw query "
                      'text linked to student ID for twelve months. Most queries are mundane, but logs '
                      'will inevitably include questions about mitigating circumstances, disability '
                      'supports, and mental-health services. Students see a cookie-style banner but no '
                      'granular opt-out from identifiable logging while still using the bot. No model '
                      'makes academic decisions. The subtle issue is purpose creep and sensitive-query '
                      'retention rather than high-stakes automation.',
     'expected_requirements': ['R005', 'R023', 'R027', 'R042', 'HE007', 'ACM003'],
     'expected_rights': ['Art8_DataProtection', 'Art7_PrivateLife'],
     'expected_charter_articles': ['Art8_DataProtection', 'Art7_PrivateLife'],
     'expected_risks': ['PrivacyBreach', 'FunctionCreep'],
     'expected_risk_categories': ['PrivacyBreach', 'FunctionCreep'],
     'info_sufficiency_expected': 3,
     'rationale': 'Low-risk campus chatbot with subtle identifiable sensitive-query logging.'},

    {'id': 'P34',
     'title': 'Clickstream Engagement Analytics without Cameras',
     'risk_level': 'Low',
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'proposal_text': "This research proposes clickstream-only 'engagement analytics' for an online "
                      'continuing-education platform: page dwell time, quiz retries, and forum posts. '
                      'No webcam or emotion recognition is used. Instructors see per-student '
                      'engagement scores that may inform outreach emails. Scores are not used for '
                      'formal grading. A subtle issue is that engagement proxies can disadvantage '
                      'students with disability-related interaction patterns or shared-device access, '
                      'and outreach based on low scores may feel surveillant. The proposal does not '
                      'discuss reasonable-accommodation effects. Data stay on the university LMS.',
     'expected_requirements': ['R027', 'R042', 'R054', 'HE007', 'ACM003'],
     'expected_rights': ['Art8_DataProtection', 'Art21_NonDiscrimination', 'Art7_PrivateLife'],
     'expected_charter_articles': ['Art8_DataProtection',
                                   'Art21_NonDiscrimination',
                                   'Art7_PrivateLife'],
     'expected_risks': ['Discrimination', 'PrivacyBreach'],
     'expected_risk_categories': ['Discrimination', 'PrivacyBreach'],
     'info_sufficiency_expected': 3,
     'rationale': 'Low-risk LMS analytics with subtle disability/discrimination pathway; tests '
                  'over/under-flagging.'},

    {'id': 'P35',
     'title': 'Synthetic Clinical Notes for NLP Training',
     'risk_level': 'Medium',
     'source': 'Illustrative case informed by synthetic EHR / clinical NLP literature and '
               'membership-inference concerns for generative clinical text.',
     'proposal_text': 'This project fine-tunes a large language model on 1.2 million de-identified '
                      'clinical notes from an Irish hospital group to generate synthetic notes for '
                      'downstream NLP shared tasks. The team claims synthetic outputs eliminate '
                      'privacy risk and plans public release of the generator. Recent research shows '
                      'membership inference and rare-condition memorisation can still leak training '
                      'patients. No empirical privacy attack evaluation is budgeted. Synthetic notes '
                      'will be used only for research benchmarks, not clinical care. Hospital legal '
                      "counsel has approved release based on the 'synthetic = safe' claim alone.",
     'expected_requirements': ['R005',
                               'R023',
                               'R027',
                               'R042',
                               'R054',
                               'AI011',
                               'HE007',
                               'HE008',
                               'ACM003',
                               'ACM008'],
     'expected_rights': ['Art8_DataProtection', 'Art7_PrivateLife', 'Art35_HealthCare'],
     'expected_charter_articles': ['Art8_DataProtection', 'Art7_PrivateLife', 'Art35_HealthCare'],
     'expected_risks': ['PrivacyBreach', 'DataBreach'],
     'expected_risk_categories': ['PrivacyBreach', 'DataBreach'],
     'info_sufficiency_expected': 3,
     'rationale': 'Medium-risk synthetic EHR release with under-tested memorisation; privacy articles '
                  'engaged.'},

    {'id': 'P36',
     'title': 'Online Exam Attention Estimation from Webcam Pose',
     'risk_level': 'Medium',
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'proposal_text': "This research estimates 'attention' during online university exams from webcam "
                      'head-pose and gaze proxies, producing a per-student attention timeline for '
                      'instructor review after the exam. Timelines are not auto-fail triggers. '
                      'Students must enable the webcam to sit the exam. Disability advocates argue '
                      'gaze proxies discriminate against neurodivergent students; the exam board '
                      'argues attention analytics are ordinary pedagogy. Whether Art.21 '
                      'non-discrimination, Art.7 private life, Art.1 dignity, or primarily '
                      'education-policy rather than Charter law applies is contested among reasonable '
                      'experts. No demographic validation is reported.',
     'expected_requirements': ['R027', 'R042', 'R043', 'R054', 'AI011', 'HE003', 'ACM004'],
     'expected_rights': ['Art7_PrivateLife',
                         'Art8_DataProtection',
                         'Art21_NonDiscrimination',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art7_PrivateLife',
                                   'Art8_DataProtection',
                                   'Art21_NonDiscrimination',
                                   'Art1_HumanDignity'],
     'expected_risks': ['PrivacyBreach', 'Discrimination', 'Surveillance'],
     'expected_risk_categories': ['PrivacyBreach', 'Discrimination', 'Surveillance'],
     'info_sufficiency_expected': 2,
     'rationale': 'Contested Medium case: attention analytics vs disability discrimination; article '
                  'set disputed.'},

    {'id': 'P37',
     'title': 'Refugee Resettlement Matching Algorithm',
     'risk_level': 'High',
     'source': 'Illustrative case informed by Annie™ MOORE / refugee-matching research and '
               'humanitarian critiques of algorithmic resettlement prioritisation.',
     'proposal_text': 'This project partners with a European resettlement NGO to rank refugee cases '
                      'for limited placement slots using employability predictions, language scores, '
                      'family composition, and health flags. Rankings influence which families are '
                      'proposed to municipalities. Nationality and religion are excluded, but language '
                      'and education features correlate with origin country. Rejected families receive '
                      'no detailed explanation. Humanitarian lawyers disagree whether this primarily '
                      'engages Art.1 dignity, Art.21 non-discrimination, Art.18 (asylum-related) '
                      'analogues via dignity/liberty, or is a legitimate scarce-resource allocation '
                      'outside Charter framing. The model has not been audited for nationality proxy '
                      'effects. Affected communities were not consulted in feature design.',
     'expected_requirements': ['R027',
                               'R042',
                               'R054',
                               'R071',
                               'R085',
                               'AI001',
                               'AI016',
                               'HE012',
                               'ACM001'],
     'expected_rights': ['Art1_HumanDignity',
                         'Art21_NonDiscrimination',
                         'Art47_RightToEffectiveRemedy',
                         'Art8_DataProtection'],
     'expected_charter_articles': ['Art1_HumanDignity',
                                   'Art21_NonDiscrimination',
                                   'Art47_RightToEffectiveRemedy',
                                   'Art8_DataProtection'],
     'expected_risks': ['Discrimination', 'Accountability', 'Dignity'],
     'expected_risk_categories': ['Discrimination', 'Accountability'],
     'info_sufficiency_expected': 2,
     'rationale': 'High-stakes humanitarian matching; Charter framing is genuinely contested among '
                  'experts.'},

    {'id': 'P38',
     'title': 'Dating-App Safety Classifier for LGBTQ+ Users in Hostile Jurisdictions',
     'risk_level': 'Medium',
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'proposal_text': 'This research builds a classifier that flags potentially entrapment-related '
                      'profiles and messages on a dating app used by LGBTQ+ people in jurisdictions '
                      'where same-sex intimacy is criminalised. Flagged chats are queued for voluntary '
                      'user warnings; the app does not notify police. False positives may chill '
                      'legitimate intimate speech (Art.11 / private life); false negatives may enable '
                      'harm. Community advisory board members disagree whether the dominant frame is '
                      'safety, expression, privacy, or non-discrimination. Training labels come from '
                      'moderator decisions in EU markets and may not transfer. The proposal leaves the '
                      'primary Charter article intentionally under-determined.',
     'expected_requirements': ['R010', 'R027', 'R042', 'R054', 'HE005', 'HE019', 'ACM020'],
     'expected_rights': ['Art7_PrivateLife',
                         'Art11_FreedomOfExpression',
                         'Art21_NonDiscrimination',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art7_PrivateLife',
                                   'Art11_FreedomOfExpression',
                                   'Art21_NonDiscrimination',
                                   'Art1_HumanDignity'],
     'expected_risks': ['PrivacyBreach', 'ExpressionHarm', 'Discrimination'],
     'expected_risk_categories': ['PrivacyBreach', 'ExpressionHarm', 'Discrimination'],
     'info_sufficiency_expected': 2,
     'rationale': 'Contested Medium safety-vs-expression case; multiple articles reasonably primary.'},

    {'id': 'P39',
     'title': 'Municipal Climate-Migration Risk Scoring',
     'risk_level': 'Medium',
     'source': 'Illustrative case informed by climate-migration foresight tools and municipal '
               'adaptation planning debates (IPCC SRCCL / urban adaptation literature).',
     'proposal_text': "This project scores neighbourhoods in a coastal EU city for 'climate-migration "
                      "pressure' using flood models, housing tenure, and demographic composition, to "
                      'prioritise adaptation spending. Scores are public. Housing advocates warn '
                      'publication will accelerate insurance retreat and stigmatise migrant-heavy '
                      'districts; planners argue transparency is required for democratic budgeting. '
                      'Whether Art.21 non-discrimination, Art.37 environment, Art.1 dignity, or '
                      'primarily environmental policy applies is contested. No individual decisions '
                      'are automated. The demographic features make disparate neighbourhood effects '
                      'likely.',
     'expected_requirements': ['R001', 'R027', 'R042', 'R054', 'HE018', 'ACM026'],
     'expected_rights': ['Art21_NonDiscrimination',
                         'Art37_EnvironmentalProtection',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art21_NonDiscrimination',
                                   'Art37_EnvironmentalProtection',
                                   'Art1_HumanDignity'],
     'expected_risks': ['Discrimination', 'EconomicHarm'],
     'expected_risk_categories': ['Discrimination', 'EconomicHarm'],
     'info_sufficiency_expected': 2,
     'rationale': 'Contested Medium planning tool; environment vs discrimination framing disputed.'},

    {'id': 'P40',
     'title': "Workplace Emotion Analytics under 'Wellbeing' Framing",
     'risk_level': 'Medium',
     'source': 'Synthetic illustrative case constructed for the AIEF evaluation corpus (2026).',
     'proposal_text': 'This research pilots camera-based emotion analytics in a Lagos business-process '
                      'outsourcing centre, framed as employee wellbeing support. Aggregated mood '
                      "dashboards go to team leads; individuals scoring repeatedly 'distressed' are "
                      'offered counselling referrals. Participation is described as voluntary but tied '
                      'to a wellness bonus. Labour advocates call it surveillance that chills union '
                      'organising; HR calls it duty-of-care. Consent voluntariness under wage pressure '
                      'is disputed. The system was validated on Western face sets only. Expected '
                      'Charter mapping (private life, data protection, fair working conditions, '
                      'dignity) is reasonably contested in weight even when articles are listed.',
     'expected_requirements': ['R001',
                               'R005',
                               'R010',
                               'R027',
                               'R042',
                               'R054',
                               'AI011',
                               'HE007',
                               'HE020',
                               'ACM003',
                               'ACM011'],
     'expected_rights': ['Art7_PrivateLife',
                         'Art8_DataProtection',
                         'Art31_FairWorkingConditions',
                         'Art1_HumanDignity'],
     'expected_charter_articles': ['Art7_PrivateLife',
                                   'Art8_DataProtection',
                                   'Art31_FairWorkingConditions',
                                   'Art1_HumanDignity'],
     'expected_risks': ['Surveillance', 'PrivacyBreach', 'EmploymentHarm'],
     'expected_risk_categories': ['Surveillance', 'PrivacyBreach', 'EmploymentHarm'],
     'info_sufficiency_expected': 3,
     'rationale': 'Medium-risk workplace affect analytics in Nigeria; consent/surveillance framing '
                  'contested.'},
]
