#!/usr/bin/env python3
"""
Task 1.1 — Populate :hasMitigation across all requirements using the auditable
risk→mitigation rule table in risk_to_mitigation_table.py.

For each of the 207 requirements, union the mitigations listed for every
:hasRisk category on that requirement. Emit a TTL fragment, then surgically
merge into ai-ethics-final.ttl (preserving file structure).

Usage:
  python ontology/populate_mitigations.py [--dry-run]
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from rdflib import Graph, Namespace, URIRef

from risk_to_mitigation_table import RISK_TO_MITIGATION

TTL = Path(__file__).parent / "ai-ethics-final.ttl"
FRAGMENT = Path(__file__).parent / "mitigation_population.ttl"
NS = Namespace("https://w3id.org/aief/")

ALL_MITIGATION_CLASSES = {
    ":Encryption",
    ":Pseudonymisation",
    ":Anonymisation",
    ":AccessControl",
    ":AuditLog",
    ":StaffTraining",
    ":GovernanceProcedure",
    ":ComplaintMechanism",
    ":IncidentResponsePlan",
    ":EthicsReviewBoard",
    ":HumanOversight",
    ":ResponsibleReleasePolicy",
    ":EnvironmentalSafeguard",
}


def _local(uri) -> str:
    s = str(uri)
    return s.rsplit("/", 1)[-1] if "/" in s else s


def sanity_check_table() -> None:
    assert len(RISK_TO_MITIGATION) == 28, (
        f"risk-category count drifted: {len(RISK_TO_MITIGATION)} != 28"
    )
    for cat, mits in RISK_TO_MITIGATION.items():
        unknown = set(mits) - ALL_MITIGATION_CLASSES
        assert not unknown, f"{cat} references unknown mitigation(s): {unknown}"


def assign_mitigations(g: Graph) -> tuple[dict[str, list[str]], Counter]:
    """
    Return ({requirement_local_name: sorted mitigation local names}, unmapped hits).
    Empty list means the requirement's risks mapped to no mitigations.
    """
    assignments: dict[str, set[str]] = defaultdict(set)
    unmapped_cats_used: Counter = Counter()
    # Ensure every requirement appears in assignments, even if empty.
    reqs = {s for s, _, _ in g.triples((None, NS.requirementID, None))}
    for req in reqs:
        rid = _local(req)
        assignments.setdefault(rid, set())
        risks = [_local(o) for o in g.objects(req, NS.hasRisk)]
        for risk in risks:
            mits = RISK_TO_MITIGATION.get(risk)
            if mits is None:
                raise KeyError(
                    f"Requirement {rid} has :hasRisk :{risk} not in RISK_TO_MITIGATION"
                )
            if not mits:
                unmapped_cats_used[risk] += 1
                continue
            for m in mits:
                assignments[rid].add(m.lstrip(":"))

    return {rid: sorted(mits) for rid, mits in assignments.items()}, unmapped_cats_used


def write_fragment(assignments: dict[str, list[str]], path: Path) -> None:
    lines = [
        "# Auto-generated by ontology/populate_mitigations.py — do not edit by hand.",
        "# Source of truth for the mapping: ontology/risk_to_mitigation_table.py",
        "PREFIX : <https://w3id.org/aief/>",
        "",
    ]
    for rid in sorted(assignments, key=lambda x: (re.sub(r"\d+", "", x), int(re.search(r"\d+", x).group()) if re.search(r"\d+", x) else 0)):
        mits = assignments[rid]
        if not mits:
            continue
        mit_csv = " , ".join(f":{m}" for m in mits)
        lines.append(f":{rid} :hasMitigation {mit_csv} .")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _format_has_mitigation(mits: list[str]) -> str:
    if len(mits) == 1:
        return f"    :hasMitigation :{mits[0]} ;"
    joined = " , ".join(f":{m}" for m in mits)
    return f"    :hasMitigation {joined} ;"


def merge_into_ttl(text: str, assignments: dict[str, list[str]]) -> str:
    """
    Surgically insert/replace :hasMitigation on each requirement block.
    Prefer placing the line immediately before the existing :hasRisk line
    (matching :R071's current style). If no :hasRisk line, append before the
    terminating '.' of the block.

    Important: only strip indented `:hasMitigation` *assertions* inside
    requirement blocks — never the top-level `:hasMitigation rdf:type
    owl:ObjectProperty` declaration.
    """

    def patch_block(rid: str, mits: list[str], src: str) -> str:
        if not mits:
            return src
        mit_line = _format_has_mitigation(mits)

        pattern = re.compile(
            rf"(:{re.escape(rid)}\s+rdf:type\s+:\w+\s*;\n)"
            rf"(.*?)"
            rf"(?=\n:[A-Za-z0-9_]+\s+rdf:type|\n###|\n# =====|\Z)",
            flags=re.S,
        )
        m = pattern.search(src)
        if not m:
            print(f"  [WARN] Could not locate block for :{rid}; skipping merge", file=sys.stderr)
            return src

        head, body = m.group(1), m.group(2)
        # Remove any existing indented :hasMitigation assertion(s) in this block only
        body = re.sub(r"^[ \t]+:hasMitigation[ \t]+[^\n]+\n", "", body, flags=re.M)

        if re.search(r"^[ \t]*:hasRisk\b", body, flags=re.M):
            body2 = re.sub(
                r"(^[ \t]*:hasRisk\b)",
                mit_line + "\n" + r"\1",
                body,
                count=1,
                flags=re.M,
            )
        else:
            body2 = re.sub(r"(\n)(\.\s*\n?)\s*$", rf"\n{mit_line}\2", body, count=1)
            if body2 == body:
                body2 = body.rstrip() + "\n" + mit_line + "\n"

        return src[: m.start()] + head + body2 + src[m.end() :]

    out = text
    for rid in sorted(assignments):
        out = patch_block(rid, assignments[rid], out)
    return out


def coverage_report(
    g: Graph,
    assignments: dict[str, list[str]],
    unmapped_cats_used: Counter,
) -> dict:
    total = len({s for s, _, _ in g.triples((None, NS.requirementID, None))})
    with_mit = sum(1 for mits in assignments.values() if mits)
    without = total - with_mit
    mit_freq = Counter()
    for mits in assignments.values():
        mit_freq.update(mits)

    print("=" * 60)
    print("Task 1.1 coverage report")
    print("=" * 60)
    print(f"Total requirements:              {total}")
    print(f"With ≥1 :hasMitigation:          {with_mit} ({100 * with_mit / total:.1f}%)")
    print(f"Unmapped (no mitigation fit):    {without}")
    print(f"Risk categories with empty map:  {sum(1 for v in RISK_TO_MITIGATION.values() if not v)}")
    if unmapped_cats_used:
        print("Unmapped category hits:")
        for cat, n in unmapped_cats_used.most_common():
            print(f"  {cat}: {n} requirement(s)")
    print("Mitigation class usage (requirement count):")
    for m, n in mit_freq.most_common():
        print(f"  :{m}: {n}")
    print("=" * 60)
    return {
        "total": total,
        "with_mitigation": with_mit,
        "unmapped": without,
        "mitigation_freq": dict(mit_freq),
    }


def verify_merged(path: Path, assignments: dict[str, list[str]]) -> None:
    g = Graph()
    g.parse(path, format="turtle")
    print(f"Merged TTL parses: {len(g)} triples")

    mismatches = []
    for rid, expected in assignments.items():
        got = sorted(_local(o) for o in g.objects(NS[rid], NS.hasMitigation))
        if got != expected:
            mismatches.append((rid, expected, got))
    if mismatches:
        print(f"[FAIL] {len(mismatches)} assignment mismatches after merge:", file=sys.stderr)
        for rid, exp, got in mismatches[:10]:
            print(f"  {rid}: expected {exp}, got {got}", file=sys.stderr)
        raise SystemExit(1)

    with_mit = len({s for s, _, _ in g.triples((None, NS.hasMitigation, None))})
    print(f"Post-merge requirements with :hasMitigation: {with_mit}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Write fragment only; do not modify ai-ethics-final.ttl")
    args = parser.parse_args()

    sanity_check_table()

    g = Graph()
    g.parse(TTL, format="turtle")
    print(f"Loaded {TTL.name}: {len(g)} triples")

    assignments, unmapped_cats_used = assign_mitigations(g)
    report = coverage_report(g, assignments, unmapped_cats_used)

    write_fragment(assignments, FRAGMENT)
    print(f"Wrote fragment: {FRAGMENT} ({sum(1 for v in assignments.values() if v)} statements)")

    if args.dry_run:
        print("Dry-run: left ai-ethics-final.ttl unchanged.")
        return

    original = TTL.read_text(encoding="utf-8")
    merged = merge_into_ttl(original, assignments)
    TTL.write_text(merged, encoding="utf-8")
    print(f"Merged into {TTL}")
    verify_merged(TTL, assignments)
    print(
        f"DONE — {report['with_mitigation']}/{report['total']} requirements now have "
        f":hasMitigation; {report['unmapped']} remain unmapped."
    )


if __name__ == "__main__":
    main()
