"""Render one AIEF assessment into four authority-specific documents,
and score documentation completeness (required fields satisfied)."""
import json, sys, os
from pathlib import Path

# Required fields per authority (from each framework's template/checklist)
TEMPLATES = {
    "REAMS": ["project_summary", "risk_level", "participant_risks",
              "data_protection", "consent_arrangements", "mitigations"],
    "FRIA":  ["intended_purpose", "affected_rights", "risk_identification",
              "severity_assessment", "mitigation_measures", "precedent_evidence"],
    "ACM_NeurIPS": ["broader_impact", "potential_misuse", "harm_mitigations"],
    "HorizonEurope": ["ethics_by_design", "data_management",
                      "social_impact", "human_oversight"],
}

def build_sections(d):
    """Map pipeline JSON -> the field pool all templates draw from."""
    a = d["assessment"]
    reqs = a.get("applicable_requirements", [])
    rights = a.get("charter_rights_at_risk", [])
    incidents = a.get("historical_precedents", [])
    mits = a.get("recommended_mitigations", [])
    risks = a.get("identified_risks", [])
    def fmt_reqs(fw=None):
        sel = [r for r in reqs if fw is None or fw.lower() in str(r.get("framework","")).lower()]
        return "\n".join(f"- {r.get('requirement_id')}: {r.get('requirement_text','')}" for r in sel) or None
    return {
        "project_summary": d.get("proposal_text", "")[:600],
        "risk_level": a.get("overall_risk_level"),
        "participant_risks": "\n".join(f"- {r.get('risk')} ({r.get('severity')})" for r in risks) or None,
        "data_protection": fmt_reqs("REAMS") or fmt_reqs(),
        "consent_arrangements": next((r.get("requirement_text") for r in reqs
                                      if "consent" in str(r.get("requirement_text","")).lower()), None),
        "mitigations": "\n".join(f"- {m.get('mitigation', m) if isinstance(m,dict) else m}" for m in mits) or None,
        "intended_purpose": a.get("risk_summary"),
        "affected_rights": "\n".join(f"- {r.get('article')}: {r.get('right_name','')}" for r in rights) or None,
        "risk_identification": "\n".join(f"- {r.get('risk')}" for r in risks) or None,
        "severity_assessment": "\n".join(f"- {r.get('risk')}: {r.get('severity')}" for r in risks) or None,
        "mitigation_measures": "\n".join(f"- {m.get('mitigation', m) if isinstance(m,dict) else m}" for m in mits) or None,
        "precedent_evidence": "\n".join(f"- {i.get('incident_id')}: {i.get('incident_title', i.get('title',''))}" for i in incidents) or None,
        "broader_impact": a.get("risk_summary"),
        "potential_misuse": "\n".join(f"- {r.get('risk')}" for r in risks) or None,
        "harm_mitigations": "\n".join(f"- {m.get('mitigation', m) if isinstance(m,dict) else m}" for m in mits) or None,
        "ethics_by_design": fmt_reqs("Horizon"),
        "data_management": fmt_reqs("REAMS"),
        "social_impact": a.get("risk_summary"),
        "human_oversight": next((r.get("requirement_text") for r in reqs
                                 if "oversight" in str(r.get("requirement_text","")).lower()), None),
    }

def main(json_path, outdir):
    d = json.load(open(json_path))
    pid = d.get("proposal_id", Path(json_path).stem)
    pool = build_sections(d)
    os.makedirs(outdir, exist_ok=True)
    scores = {}
    for authority, fields in TEMPLATES.items():
        lines = [f"# {authority} ethics documentation — {pid}",
                 f"Generated by AIEF from a single harmonised assessment.\n"]
        filled = 0
        for f in fields:
            v = pool.get(f)
            lines.append(f"## {f.replace('_',' ').title()}\n{v or '[NOT DERIVABLE FROM ASSESSMENT — requires manual input]'}\n")
            filled += bool(v)
        scores[authority] = (filled, len(fields))
        open(f"{outdir}/{pid}_{authority}.md", "w").write("\n".join(lines))
    print(f"{pid} completeness: " + " | ".join(
        f"{a}: {f}/{t} ({100*f//t}%)" for a, (f, t) in scores.items()))
    return scores

if __name__ == "__main__":
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("../evaluation/results/llama-3.3-70b")
    outdir = "../evaluation/generated-documentation"
    agg = {}
    for jf in sorted(src.glob("P*_full.json")):
        for a, (f, t) in main(jf, outdir).items():
            agg.setdefault(a, []).append(f / t)
    print("\n=== MEAN COMPLETENESS ===")
    for a, vals in agg.items(): print(f"{a}: {100*sum(vals)/len(vals):.0f}% (n={len(vals)})")
